services:
  - type: web
    name: loomis-ai-backend
    runtime: node
    repo: https://github.com/Abhigrgx/Loomis-AI
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_VERSION
        value: v1
      - key: FRONTEND_URL
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false

databases: []
